"""What gets archived, where it lands, and how it converts to and from JSON.

This module is the schema of the archive. Adding a collection to LOOP means
adding one :class:`ArchiveKind` here; everything downstream — the signal hooks,
``export``, ``verify``, ``rebuild``, ``replay`` — is driven off this table and
needs no edit.

Two things are deliberately *not* archived:

**Derived collections.** ``ml_embeddings`` (regenerated by
``backfill_embeddings``), ``doi_mappings`` (regenerated from recipe literature),
and ``Material.latest_trial_date`` (regenerated by ``backfill_trial_dates``) are
projections of archived data. Storing them would double the archive's size and
guarantee spurious drift, since they are written by paths that deliberately
bypass the document layer.

**Transient queues.** ``synthesis_parse_jobs``, ``model_retrain_jobs``, and
``aflow_cache`` describe work in flight or an external API's cached answer.
Losing them costs a re-run, not a record.

``synthesis_parse_cache`` *is* archived despite looking like a cache: it maps
route text to discrete steps, and recipe AUIDs are computed from those steps. A
lost cache means the LLM re-parses and may produce different steps, which would
silently fork every affected recipe onto a new AUID.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Callable, Iterable, Optional

from bson import ObjectId

# --------------------------------------------------------------------------
# Path helpers
# --------------------------------------------------------------------------

def sanitize(text: str) -> str:
    """Filesystem-safe token: colons (from AUIDs) become hyphens.

    Mirrors :func:`catalog.api_download._sanitize` so the archive tree and the
    zip downloads use identical folder names.
    """
    return (text or "").replace(":", "-")


def material_dir(material_auid: str) -> str:
    return f"materials/{sanitize(material_auid)}"


def recipe_dir(recipe_auid: str) -> str:
    """``M:abc:R:7f8e`` -> ``materials/M-abc/recipes/R-7f8e``.

    Uses :func:`catalog.auid.split_recipe_id` rather than string surgery so a
    malformed id raises here instead of silently producing a wrong path.
    """
    from catalog import auid as auid_mod

    material, short = auid_mod.split_recipe_id(recipe_auid)
    return f"{material_dir(material)}/recipes/R-{sanitize(short)}"


def _shard(digest: str) -> str:
    """Two levels of 2-hex fan-out, so no directory holds 100k entries."""
    return f"{digest[:2]}/{digest[2:4]}"


def blob_path(sha256: str, ext: str = "") -> str:
    return f"blobs/sha256/{_shard(sha256)}/{sha256}{ext or ''}"


# --------------------------------------------------------------------------
# Payload projection
# --------------------------------------------------------------------------

def _storable_datetime(value: datetime) -> datetime:
    """Round-trip a datetime through BSON's representation, in memory.

    This exists because the archive is written *before* Mongo, from the
    in-memory document, but must equal what Mongo will hand back afterwards.
    BSON stores a datetime as milliseconds since the epoch in UTC, so the
    driver silently does two things on the way in:

    1. Truncates microseconds to milliseconds.
    2. Treats a naive datetime as UTC, and (with ``tz_aware=True``, which LOOP
       sets) returns it as an aware UTC datetime.

    Without applying the same two transforms here, every record containing a
    timestamp would differ between disk and database — ``verify`` would report
    the entire catalog as drifted, and an export-rebuild-export cycle would
    never converge. The failure is invisible until you compare bytes, which is
    exactly what the round-trip test does.
    """
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    else:
        value = value.astimezone(timezone.utc)
    return value.replace(microsecond=(value.microsecond // 1000) * 1000)


#: Wrapper key for a datetime that the schema cannot type on the way back in.
#: Safe as a sentinel because MongoEngine rejects ``$``-prefixed keys in a
#: ``DictField`` ("keys may not startswith \"$\" characters"), so no legitimate
#: user data can produce this shape.
DATE_TAG = "$date"


def _plain_untyped(value: Any) -> Any:
    """Archive a value the schema cannot describe, preserving its type.

    Used for anything inside a ``DictField`` — arbitrary user or instrument
    metadata, where MongoEngine declares no inner types. A bare ISO string
    would be indistinguishable from a string that merely looks like a date, so
    a datetime here is tagged and decoded on the way back. Everywhere the
    schema *does* know the type, :func:`_plain_typed` writes a plain readable
    string instead.
    """
    if isinstance(value, ObjectId):
        return str(value)
    if isinstance(value, datetime):
        return {DATE_TAG: _storable_datetime(value).isoformat()}
    if isinstance(value, dict):
        return {key: _plain_untyped(val) for key, val in value.items()}
    if isinstance(value, (list, tuple)):
        return [_plain_untyped(item) for item in value]
    return value


def _plain_typed(value: Any) -> Any:
    """Archive a value whose type the schema will restore on rebuild."""
    if isinstance(value, ObjectId):
        return str(value)
    if isinstance(value, datetime):
        return _storable_datetime(value)
    if isinstance(value, dict):
        return {key: _plain_typed(val) for key, val in value.items()}
    if isinstance(value, (list, tuple)):
        return [_plain_typed(item) for item in value]
    return value


def _field_map(document_class) -> dict:
    """Map stored (db_field) names to their MongoEngine field definitions.

    ``to_mongo()`` emits db_field names, while ``_fields`` is keyed by Python
    attribute name; they differ wherever a field declares ``db_field=``.
    """
    fields = getattr(document_class, "_fields", {}) or {}
    mapping = {}
    for name, field in fields.items():
        mapping[getattr(field, "db_field", None) or name] = field
    return mapping


def _project_value(value: Any, field: Any) -> Any:
    """Archive one value, using its field definition to decide the encoding.

    ``field is None`` means the schema has nothing to say about this value —
    either it sits inside a ``DictField``, or the document has ``strict: False``
    and picked up a key with no declaration. Either way the type cannot be
    recovered from the schema on rebuild, so it is tagged.
    """
    from mongoengine import fields as me_fields

    if field is None:
        return _plain_untyped(value)
    if value is None:
        return None

    if isinstance(field, me_fields.EmbeddedDocumentField):
        if isinstance(value, dict):
            return _project_mapping(value, _field_map(field.document_type))
        return _plain_typed(value)

    if isinstance(field, (me_fields.ListField, me_fields.SortedListField)):
        if isinstance(value, (list, tuple)):
            return [_project_value(item, field.field) for item in value]
        return _plain_typed(value)

    # MapField is a DictField with a declared value type; a plain DictField
    # has field=None, which routes its contents to the untyped encoder.
    if isinstance(field, me_fields.DictField):
        if isinstance(value, dict):
            inner = getattr(field, "field", None)
            return {key: _project_value(val, inner) for key, val in value.items()}
        return _plain_typed(value)

    return _plain_typed(value)


def _project_mapping(raw: dict, field_map: dict) -> dict:
    return {
        key: _project_value(value, field_map.get(key))
        for key, value in raw.items()
    }


def document_payload(document, *, drop: Iterable[str] = ()) -> dict:
    """Serialize a MongoEngine document to a plain, archivable dict.

    ``to_mongo()`` gives the exact BSON that would be stored, which is what we
    want: the archive records what Mongo holds, not what a hand-written
    serializer thinks it should hold. New fields are picked up automatically.
    """
    raw = document.to_mongo().to_dict()
    raw.pop("_cls", None)
    for key in drop:
        raw.pop(key, None)
    return _project_mapping(raw, _field_map(type(document)))


def raw_payload(document_class, raw: dict, *, drop: Iterable[str] = ()) -> dict:
    """Project a document read straight from pymongo, with no defaults invented.

    Use this for anything that *reads* existing data — export, verify, rebuild
    comparisons. :func:`document_payload` goes through ``to_mongo()``, which
    materializes each field's ``default`` for keys the stored document does not
    have. For a ``DateTimeField(default=_utc_now)`` that means a brand-new
    timestamp on every call, so the same untouched document projects to
    different bytes each time and the archive can never converge.

    That is not hypothetical: documents written by the raw ``bulk_write`` paths
    (``import_chemscreen``, ``import_chaos_data``) and by
    ``upsert_user_affiliations`` have no ``created_at``/``updated_at`` stored at
    all.

    ``document_payload`` remains correct on the *write* path, where the document
    is about to be saved and ``to_mongo()`` is exactly what will be stored.
    """
    data = {key: value for key, value in raw.items() if key != "_cls"}
    for key in drop:
        data.pop(key, None)
    return _project_mapping(data, _field_map(document_class))


def embedded_payload(document) -> dict:
    """Serialize an embedded document (trial, literature, DFT) to a dict."""
    raw = document.to_mongo().to_dict()
    raw.pop("_cls", None)
    return _project_mapping(raw, _field_map(type(document)))


def decode_tagged(value: Any) -> Any:
    """Invert :func:`_plain_untyped`'s tagging when loading an archived record.

    Applied on rebuild and replay before the document is constructed, so a
    datetime that was stored inside an untyped ``DictField`` comes back as a
    datetime rather than the string it would otherwise degrade into.
    """
    if isinstance(value, dict):
        if len(value) == 1 and DATE_TAG in value:
            raw = value[DATE_TAG]
            if isinstance(raw, str):
                try:
                    return datetime.fromisoformat(raw)
                except ValueError:
                    return raw
            return raw
        return {key: decode_tagged(val) for key, val in value.items()}
    if isinstance(value, list):
        return [decode_tagged(item) for item in value]
    return value


# --------------------------------------------------------------------------
# Kind table
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class ArchiveKind:
    """One archivable record type.

    ``key_of`` and ``path_of`` take the *payload dict*, not the document, so
    that ``rebuild`` and ``replay`` — which only ever see JSON read back from
    disk — can compute paths without reconstructing a document first.
    """

    name: str
    collection: str
    path_of: Callable[[dict], str]
    key_of: Callable[[dict], str]
    db_alias: str = "default"
    id_is_objectid: bool = False
    #: Fields stripped before archiving because they are derived elsewhere.
    drop_fields: tuple[str, ...] = ()
    #: Dotted import path of the MongoEngine Document class. Resolved lazily so
    #: this module stays importable before the app registry is ready.
    document_path: str = ""
    #: Embedded child kinds are written by their parent, not by their own hook.
    written_by_parent: bool = False

    def document_class(self):
        module_name, _, class_name = self.document_path.rpartition(".")
        module = __import__(module_name, fromlist=[class_name])
        return getattr(module, class_name)


def _material_path(payload: dict) -> str:
    return f"{material_dir(payload['_id'])}/material.json"


def _recipe_path(payload: dict) -> str:
    return f"{recipe_dir(payload['_id'])}/recipe.json"


def _trial_path(payload: dict) -> str:
    return (
        f"{recipe_dir(payload['recipe_auid'])}"
        f"/trials/{sanitize(payload['trial_id'])}/trial.json"
    )


def _literature_path(payload: dict) -> str:
    return (
        f"{recipe_dir(payload['recipe_auid'])}"
        f"/literature/{sanitize(payload['lit_id'])}.json"
    )


def _user_dir(payload: dict) -> str:
    # Username, not user_id: the archive should stay legible, and a Django
    # user id is meaningless once SQLite is gone.
    return f"users/{sanitize(payload.get('uploaded_by_username') or payload.get('username') or 'unknown')}"


KINDS: dict[str, ArchiveKind] = {}


def _register(kind: ArchiveKind) -> ArchiveKind:
    KINDS[kind.name] = kind
    return kind


MATERIAL = _register(ArchiveKind(
    name="material",
    collection="materials",
    document_path="catalog.documents.Material",
    path_of=_material_path,
    key_of=lambda p: p["_id"],
    # Maintained by Recipe.save()'s raw $max update and rebuilt by
    # `backfill_trial_dates`; archiving it would drift on every trial write.
    drop_fields=("latest_trial_date",),
))

RECIPE = _register(ArchiveKind(
    name="recipe",
    collection="recipes",
    document_path="catalog.documents.Recipe",
    path_of=_recipe_path,
    key_of=lambda p: p["_id"],
    # trials[] and literature[] are exploded into their own files by the
    # recipe writer; recipe.json keeps only the id lists.
    drop_fields=("trials", "literature"),
))

TRIAL = _register(ArchiveKind(
    name="trial",
    collection="recipes",
    path_of=_trial_path,
    key_of=lambda p: f"{p['recipe_auid']}/{p['trial_id']}",
    written_by_parent=True,
))

LITERATURE = _register(ArchiveKind(
    name="literature",
    collection="recipes",
    path_of=_literature_path,
    key_of=lambda p: f"{p['recipe_auid']}/{p['lit_id']}",
    written_by_parent=True,
))

RAW_FILE = _register(ArchiveKind(
    name="raw_file",
    collection="raw_files",
    document_path="catalog.raw_db.RawFile",
    db_alias="raw",
    path_of=lambda p: f"raw-files/{_shard(p['_id'])}/{p['_id']}.json",
    key_of=lambda p: p["_id"],
))

SYNTHESIS_PREDICTION = _register(ArchiveKind(
    name="synthesis_prediction",
    collection="synthesis_predictions",
    document_path="catalog.documents.SynthesisPrediction",
    path_of=lambda p: f"synthesis-predictions/{sanitize(p['_id'])}.json",
    key_of=lambda p: p["_id"],
))

SYNTHESIS_PARSE_CACHE = _register(ArchiveKind(
    name="synthesis_parse_cache",
    collection="synthesis_parse_cache",
    document_path="catalog.documents.SynthesisParseCache",
    path_of=lambda p: f"synthesis-cache/{_shard(p['_id'])}/{p['_id']}.json",
    key_of=lambda p: p["_id"],
))

MODEL_VERSION = _register(ArchiveKind(
    name="model_version",
    collection="model_versions",
    document_path="catalog.documents.ModelVersion",
    path_of=lambda p: f"models/versions/{sanitize(p['_id'])}.json",
    key_of=lambda p: p["_id"],
))

MODEL_FEEDBACK = _register(ArchiveKind(
    name="model_feedback",
    collection="model_feedback",
    document_path="catalog.documents.ModelFeedback",
    path_of=lambda p: f"models/feedback/{sanitize(p['_id'])}.json",
    key_of=lambda p: p["_id"],
))

XRD_ANALYSIS_JOB = _register(ArchiveKind(
    name="xrd_analysis_job",
    collection="xrd_analysis_jobs",
    document_path="catalog.documents.XRDAnalysisJob",
    id_is_objectid=True,
    # Keyed by the content-addressed analysis_id, not the ObjectId: it is
    # stable across a rebuild and meaningful to a human reading the tree.
    path_of=lambda p: f"xrd-analyses/{sanitize(p['analysis_id'])}/job.json",
    key_of=lambda p: p["analysis_id"],
))

XRD_ANALYSIS_REVIEW = _register(ArchiveKind(
    name="xrd_analysis_review",
    collection="xrd_analysis_reviews",
    document_path="catalog.documents.XRDAnalysisReview",
    id_is_objectid=True,
    path_of=lambda p: (
        f"xrd-analyses/{sanitize(p['analysis_id'])}/reviews/{p['_id']}.json"
    ),
    key_of=lambda p: p["_id"],
))

USER_AFFILIATION = _register(ArchiveKind(
    name="user_affiliation",
    collection="user_affiliations",
    document_path="catalog.documents.UserAffiliation",
    id_is_objectid=True,
    path_of=lambda p: f"users/{sanitize(p['username'])}/affiliations.json",
    key_of=lambda p: p["username"],
))

USER_PRECURSOR = _register(ArchiveKind(
    name="user_precursor",
    collection="user_precursors",
    document_path="catalog.documents.UserPrecursor",
    id_is_objectid=True,
    path_of=lambda p: f"{_user_dir(p)}/precursors/{p['_id']}.json",
    key_of=lambda p: p["_id"],
))

USER_PROTOCOL = _register(ArchiveKind(
    name="user_protocol",
    collection="user_protocols",
    document_path="catalog.documents.UserProtocol",
    id_is_objectid=True,
    path_of=lambda p: f"{_user_dir(p)}/protocols/{p['_id']}.json",
    key_of=lambda p: p["_id"],
))

# Django-side accounts (users, groups, API keys) live in SQLite, not MongoDB.
# They are archived by `rebuild.export_auth()` as a Django fixture rather than
# through this table, because nothing here can describe a non-MongoEngine
# model and no signal hook can reach one. Deliberately not registered as a
# kind: an entry here that `export` silently skipped would imply coverage that
# did not exist.


#: Kinds whose own ``save()`` should fire an archive write. Excludes embedded
#: children (written by their parent) and the Django-side user roster.
HOOKED_KINDS: tuple[ArchiveKind, ...] = tuple(
    kind for kind in KINDS.values()
    if kind.document_path and not kind.written_by_parent
)

#: Collections rebuilt from archived data rather than archived directly.
DERIVED_COLLECTIONS: tuple[str, ...] = (
    "ml_embeddings",
    "doi_mappings",
    "synthesis_parse_jobs",
    "model_retrain_jobs",
    "aflow_cache",
)


def kind(name: str) -> ArchiveKind:
    try:
        return KINDS[name]
    except KeyError:
        raise KeyError(
            f"Unknown archive kind {name!r}. Known kinds: {sorted(KINDS)}"
        ) from None


def kind_for_document(document) -> Optional[ArchiveKind]:
    """Resolve the kind for a MongoEngine document instance, or ``None``."""
    collection = document._meta.get("collection")
    for candidate in HOOKED_KINDS:
        if candidate.collection == collection:
            return candidate
    return None


__all__ = [
    "ArchiveKind",
    "DATE_TAG",
    "DERIVED_COLLECTIONS",
    "decode_tagged",
    "HOOKED_KINDS",
    "KINDS",
    "LITERATURE",
    "MATERIAL",
    "RAW_FILE",
    "RECIPE",
    "TRIAL",
    "blob_path",
    "document_payload",
    "embedded_payload",
    "kind",
    "kind_for_document",
    "material_dir",
    "recipe_dir",
    "sanitize",
]
