"""
Django settings for Loop project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')


def env_list(name, default=""):
    raw = os.getenv(name, default)
    return [p.strip() for p in raw.replace(" ", ",").split(",") if p.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'


# Subpath config: "" for localhost, "/loop" in prod
SUBPATH = os.environ.get("DJANGO_SUBPATH", "").rstrip("/")  # set to "/loop" in prod

if SUBPATH:
    FORCE_SCRIPT_NAME = SUBPATH           # makes reverse()/resolve_url add the prefix
    STATIC_URL = f"{SUBPATH}/static/"
    MEDIA_URL  = f"{SUBPATH}/media/"
else:
    STATIC_URL = "/static/"
    MEDIA_URL  = "/media/"

# Use route NAMES so Django will reverse them (and pick up FORCE_SCRIPT_NAME)
LOGIN_URL = "login"              # not a path; this is the auth view name
LOGIN_REDIRECT_URL = "index"     # your catalog index route name
LOGOUT_REDIRECT_URL = "index"

# The absolute path to the directory where collectstatic will collect static files for deployment.
STATIC_ROOT = Path(os.environ.get("STATIC_ROOT", str(BASE_DIR / "staticfiles")))

# For hard disk file storage
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", str(BASE_DIR / "media")))

# Timestamped upload archive — one folder per successful upload.
# Set RAW_UPLOADS_ROOT= (empty) to disable archiving.
RAW_UPLOADS_ROOT = os.environ.get("RAW_UPLOADS_ROOT", str(BASE_DIR / "raw-uploads"))

# ---------------------------------------------------------------------------
# JSON archive — the durable source of truth (see catalog/archive/).
#
# Every catalog write lands here as sorted, indented JSON *before* it reaches
# MongoDB, which is treated as a rebuildable index over this tree.
# `manage.py loop_archive rebuild` reconstructs the database from it.
# ---------------------------------------------------------------------------
ARCHIVE_ROOT = os.environ.get("ARCHIVE_ROOT", str(BASE_DIR / "archive"))

# Master switch. Off means no archive writes at all — useful for unit tests
# that only exercise Mongo behavior.
ARCHIVE_ENABLED = os.environ.get("ARCHIVE_ENABLED", "1") != "0"

# When True (the default and the intended production setting), a failed
# archive write aborts the request and MongoDB is never touched — that is what
# makes the archive authoritative rather than advisory. Set False only to keep
# uploads flowing through a disk incident; failures are then recorded in
# ARCHIVE_ROOT/.state/drift.json for `loop_archive verify` to surface.
ARCHIVE_REQUIRED = os.environ.get("ARCHIVE_REQUIRED", "1") != "0"

# fsync every archive record and journal line. Disable only where durability is
# already guaranteed by other means; bulk operations turn it off per-call.
ARCHIVE_FSYNC = os.environ.get("ARCHIVE_FSYNC", "1") != "0"

# Path to the CHAOS/AFLOW SQLite database for periodic computational data import.
# Leave empty to disable the file watcher and import command.
CHAOS_DB_PATH = os.environ.get("CHAOS_DB_PATH", "")
CHEMSCREEN_ROOT = os.environ.get("CHEMSCREEN_ROOT", "") or str(
    BASE_DIR / "vendor" / "ChemScreen"
)
CHEMSCREEN_PREDICTIONS_PATH = os.environ.get("CHEMSCREEN_PREDICTIONS_PATH", "")
CHEMSCREEN_PREDICTION_METRIC = os.environ.get(
    "CHEMSCREEN_PREDICTION_METRIC", "ML_Predicted"
)
CHEMSCREEN_MODEL_NAME = os.environ.get("CHEMSCREEN_MODEL_NAME", "ChemScreen")
CHEMSCREEN_MODEL_DIR = os.environ.get(
    "CHEMSCREEN_MODEL_DIR",
    str(BASE_DIR / "var" / "chemscreen-models"),
)
CHEMSCREEN_AUTOTRAIN_ENABLED = (
    os.environ.get("CHEMSCREEN_AUTOTRAIN_ENABLED", "1") != "0"
    and "test" not in sys.argv
)
CHEMSCREEN_RETRAIN_WORKER = os.environ.get("CHEMSCREEN_RETRAIN_WORKER", "1") != "0"
CHEMSCREEN_RETRAIN_POLL_SECONDS = float(
    os.environ.get("CHEMSCREEN_RETRAIN_POLL_SECONDS", "15")
)
CHEMSCREEN_RETRAIN_DEBOUNCE_SECONDS = float(
    os.environ.get("CHEMSCREEN_RETRAIN_DEBOUNCE_SECONDS", "15")
)
CHEMSCREEN_MIN_TRAINING_ROWS = int(
    os.environ.get("CHEMSCREEN_MIN_TRAINING_ROWS", "20")
)
CHEMSCREEN_RF_ESTIMATORS = int(os.environ.get("CHEMSCREEN_RF_ESTIMATORS", "100"))
CHEMSCREEN_RF_MAX_DEPTH = int(os.environ.get("CHEMSCREEN_RF_MAX_DEPTH", "10"))
CHEMSCREEN_RF_MIN_SAMPLES_LEAF = int(
    os.environ.get("CHEMSCREEN_RF_MIN_SAMPLES_LEAF", "2")
)
CHEMSCREEN_RF_N_JOBS = int(os.environ.get("CHEMSCREEN_RF_N_JOBS", "-1"))
CHEMSCREEN_PROMOTION_MAE_TOLERANCE = float(
    os.environ.get("CHEMSCREEN_PROMOTION_MAE_TOLERANCE", "0")
)
CHEMSCREEN_EFA_REWARD_TOLERANCE = float(
    os.environ.get("CHEMSCREEN_EFA_REWARD_TOLERANCE", "5")
)
CHEMSCREEN_DEED_REWARD_TOLERANCE = float(
    os.environ.get("CHEMSCREEN_DEED_REWARD_TOLERANCE", "2")
)
CHEMSCREEN_REWARD_WEIGHT = float(os.environ.get("CHEMSCREEN_REWARD_WEIGHT", "1.25"))
CHEMSCREEN_FLAG_WEIGHT = float(os.environ.get("CHEMSCREEN_FLAG_WEIGHT", "2"))

# AFLOW's public AFLUX API supplies formation/entropy inputs and provenance.
# EFA and DEED are model outputs; they are not direct AFLUX properties.
AFLOW_API_ENABLED = os.environ.get("AFLOW_API_ENABLED", "1") != "0"
AFLOW_API_BASE_URL = os.environ.get(
    "AFLOW_API_BASE_URL", "https://aflow.org/API/aflux/"
)
AFLOW_API_TIMEOUT = float(os.environ.get("AFLOW_API_TIMEOUT", "12"))
AFLOW_RESULT_LIMIT = int(os.environ.get("AFLOW_RESULT_LIMIT", "25"))
AFLOW_CACHE_HOURS = float(os.environ.get("AFLOW_CACHE_HOURS", "168"))
AFLOW_REFRESH_PER_TRAINING_JOB = int(
    os.environ.get("AFLOW_REFRESH_PER_TRAINING_JOB", "10")
)

# Shared site shell (header, nav, sidebar, footer) fetched from the group
# site at request time; see catalog/templatetags/s4e_shell.py. Empty URL =
# fetch nothing and use the committed copies (local development).
S4E_SHELL_URL = os.environ.get("S4E_SHELL_URL", "https://s4e.ai/")
S4E_SHELL_CACHE_SECONDS = int(os.environ.get("S4E_SHELL_CACHE_SECONDS", "600"))

# The dev deployment runs against a clone of production, real password hashes
# included, so the admin and the open registration form are liabilities there
# rather than features. With this on, loop/urls.py leaves those routes out of the
# URL conf entirely -- absent, not permission-gated, so there is no form to
# attack. Off by default: production and normal local development are unchanged.
DEV_LOCKDOWN = os.environ.get("DEV_LOCKDOWN", "0") == "1"


ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
# Django's test Client and some tooling use this host.
if DEBUG and "testserver" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = [*ALLOWED_HOSTS, "testserver"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Add our new application
    # This object was created for us in in /catalog/apps.py
    'catalog.apps.CatalogConfig',
    'django.contrib.humanize',
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "loop.middleware.ApiTokenAuthMiddleware",
    "loop.middleware.ApprovedGateMiddleware",
    # After the auth middlewares (including the API-key one) so archive journal
    # entries are attributed to the resolved user rather than "anonymous".
    "loop.middleware.ArchiveContextMiddleware",
]

APPROVED_GROUP_NAME = "Approved"
APPROVED_BYPASS_SUPERUSERS = True
AWAITING_APPROVAL_URL_NAME = "awaiting_approval"

ROOT_URLCONF = 'loop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loop.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.environ.get("SQLITE_PATH", str(BASE_DIR / "db.sqlite3"))),
    }
}

CACHES = {
    "default": {
        # Redis (shared across workers) when REDIS_URL is set — required for
        # accurate API throttling under multi-process serving; falls back to a
        # file-based cache for single-process dev.
        "BACKEND": (
            "django_redis.cache.RedisCache"
            if os.environ.get("REDIS_URL")
            else "django.core.cache.backends.filebased.FileBasedCache"
        ),
        "LOCATION": os.environ.get(
            "REDIS_URL", os.environ.get("DJANGO_CACHE_DIR", "/tmp/django_cache")
        ),
        "OPTIONS": (
            {"CLIENT_CLASS": "django_redis.client.DefaultClient"}
            if os.environ.get("REDIS_URL")
            else {}
        ),
        "TIMEOUT": 300,
    }
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "catalog.api.authentication.APIKeyAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "catalog.api.throttling.AnonymousIPRateThrottle",
        "catalog.api.throttling.AuthenticatedIPRateThrottle",
        "catalog.api.throttling.APIKeyRateThrottle",
        "catalog.api.throttling.SessionUserRateThrottle",
    ],
    "EXCEPTION_HANDLER": "catalog.api.exceptions.problem_exception_handler",
    # Production has one trusted reverse proxy in front of the loopback-bound
    # Gunicorn port. Override this if the deployment adds another proxy hop.
    "NUM_PROXIES": int(os.environ.get("API_NUM_PROXIES", "1")),
}

LOOP_API_ANON_IP_RATE = os.environ.get("API_ANON_IP_RATE", "60/min")
LOOP_API_AUTH_IP_RATE = os.environ.get("API_AUTH_IP_RATE", "1200/min")
LOOP_API_KEY_RATE = os.environ.get("API_KEY_RATE", "600/min")
LOOP_API_SESSION_USER_RATE = os.environ.get("API_SESSION_USER_RATE", "600/min")

SPECTACULAR_SETTINGS = {
    "TITLE": "LOOP API",
    "DESCRIPTION": (
        "Versioned read/write access to LOOP materials, experimental, "
        "literature, and computational records."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Renamed message tag correspondences to play nice with Bootstrap
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Static file serving.
# https://whitenoise.readthedocs.io/en/stable/django.html#add-compression-and-caching-support
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
        },
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

if DEBUG:
    WHITENOISE_AUTOREFRESH = True

FILE_UPLOAD_PERMISSIONS = 0o644  # rw-r--r-- (no execute permissions)
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755  # rwxr-xr-x (directories need execute for traversal)

# trust your real host & HTTPS when behind a proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# good to have when serving forms from your domain
CSRF_TRUSTED_ORIGINS = (
    [f"http://{h}" for h in ALLOWED_HOSTS if "." in h or "localhost" in h] +
    [f"https://{h}" for h in ALLOWED_HOSTS if "." in h]
)

if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://127.0.0.1:8000",
        "http://localhost:8000",
    ]

#-- Email Settings --

# Default: print emails to console in dev
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"  # default in dev
)
DEFAULT_FROM_EMAIL   = os.environ.get("DEFAULT_FROM_EMAIL", "Loop <noreply@loop.mintaka.arch.jhu.edu>")
EMAIL_HOST           = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT           = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER      = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD  = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS        = os.environ.get("EMAIL_USE_TLS", "1") == "1"
EMAIL_USE_SSL        = os.environ.get("EMAIL_USE_SSL", "0") == "1"
EMAIL_TIMEOUT        = 10

# Optional niceties
EMAIL_SUBJECT_PREFIX = "[Loop]"

# avoid infinite redirect in dev / localhost
if os.environ.get("DJANGO_DEBUG") == "True":
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_DOMAIN = None

# Toggle for the on-write embedding refresh hooks in catalog/signals.py.
# Set EMBEDDINGS_ON_WRITE=0 in the environment to bypass the sentence-
# transformers load on uploads (useful for tests, low-RAM dev containers,
# or any environment where the backfill command is the only thing expected
# to populate ml_embeddings).
EMBEDDINGS_ON_WRITE = os.environ.get("EMBEDDINGS_ON_WRITE", "1") != "0"

# Preload the sentence-transformers model in a background thread during app
# startup so the first semantic-search request doesn't pay the ~5s
# model-load tax. Disabled automatically for management commands that don't
# serve HTTP traffic. Set EMBEDDINGS_PRELOAD=0 to opt out entirely.
EMBEDDINGS_PRELOAD = os.environ.get("EMBEDDINGS_PRELOAD", "1") != "0"

# Minimum cosine score required for a semantic-search hit to surface on the
# browse page. For sentence-transformers/all-MiniLM-L6-v2 on short structured
# material/recipe text, observed scores cluster as:
#   >= 0.70   strong match (synonym / direct term overlap)
#   0.60-0.70 related (same domain, partial overlap)
#   0.50-0.60 weak / thematic noise
#   <  0.50   unrelated
# The default 0.55 trims the worst noise while leaving borderline-related
# hits visible. Lower it if the catalog is small enough that every hit
# matters; raise it as the dataset grows and noise piles up.
SEMANTIC_SCORE_THRESHOLD = float(os.environ.get("SEMANTIC_SCORE_THRESHOLD", "0.55"))

# --- Synthesis-route LLM discretization (OpenRouter; trial run) --------------
# Batch uploads store the free-form "Synthesis route" as a single ``other`` step
# and enqueue a background job. When enabled, the worker
# (catalog/synthesis_worker.py) calls an LLM via OpenRouter to split that blob
# into the typed steps a manual upload produces. Ships DISABLED; any failure
# falls back to the single ``other`` step so data is never lost.
#   SYNTHESIS_LLM_ENABLED  gate the LLM call at all (needs OPENROUTER_API_KEY).
#   SYNTHESIS_LLM_WORKER   start the in-process background worker thread.
SYNTHESIS_LLM_ENABLED = os.environ.get("SYNTHESIS_LLM_ENABLED", "0") != "0"
SYNTHESIS_LLM_WORKER = os.environ.get("SYNTHESIS_LLM_WORKER", "0") != "0"
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
OPENROUTER_MODEL = os.environ.get("OPENROUTER_MODEL", "google/gemini-2.5-flash")
OPENROUTER_BASE_URL = os.environ.get(
    "OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1"
)
SYNTHESIS_LLM_TIMEOUT = float(os.environ.get("SYNTHESIS_LLM_TIMEOUT", "60"))
SYNTHESIS_LLM_POLL_SECONDS = float(os.environ.get("SYNTHESIS_LLM_POLL_SECONDS", "15"))
SYNTHESIS_LLM_MAX_ATTEMPTS = int(os.environ.get("SYNTHESIS_LLM_MAX_ATTEMPTS", "3"))

# --- XRD analysis worker -----------------------------------------------------
# ``catalog/apps.py`` starts the queue-draining thread behind
# ``getattr(settings, "XRD_ANALYSIS_WORKER", False)``. The name was never bound
# here, so the getattr default always won: submissions were accepted, persisted
# as ``queued``, and then never executed by any deployment. Binding it makes the
# thread reachable; it stays OFF by default so enabling the worker is a
# deliberate deployment decision, matching SYNTHESIS_LLM_WORKER above.
#
# Enabling it is necessary but not sufficient -- the refinement step also needs
# GSAS-II importable (see GSAS2_PATH) and a reference-phase library covering the
# chemistry being measured. See docs/xrd_analysis/DEPLOYMENT_GAPS.md.
XRD_ANALYSIS_WORKER = os.environ.get("XRD_ANALYSIS_WORKER", "0") != "0"

# MongoDB Configuration
import mongoengine
from urllib.parse import urlparse, urlunparse

MONGODB_URI = os.environ.get("MONGODB_URI", "mongodb://localhost:27017/loop")
mongoengine.connect(host=MONGODB_URI, tz_aware=True)


def _default_raw_uri(primary_uri: str) -> str:
    """Derive a sensible ``loop_raw`` URI from the primary Mongo URI.

    Keeps host/port/auth identical to the main DB and just swaps the path to
    ``/loop_raw``. This means Docker users only need to set ``MONGODB_URI``
    and the raw connection Just Works against the same Mongo instance.
    """
    parsed = urlparse(primary_uri)
    return urlunparse(parsed._replace(path="/loop_raw"))


# Flat "Raw" database used as a portable file-level backup. Lives under the
# ``raw`` MongoEngine alias; see catalog/raw_db.py. Defaults to the same host
# as ``MONGODB_URI`` so Docker and local dev share a single config knob.
MONGODB_RAW_URI = os.environ.get("MONGODB_RAW_URI", _default_raw_uri(MONGODB_URI))
mongoengine.connect(alias="raw", host=MONGODB_RAW_URI, tz_aware=True)
