"""
Django settings for Loop project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')


def env_list(name, default=""):
    raw = os.getenv(name, default)
    return [p.strip() for p in raw.replace(" ", ",").split(",") if p.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'


# Subpath config: "" for localhost, "/loop" in prod
SUBPATH = os.environ.get("DJANGO_SUBPATH", "").rstrip("/")  # set to "/loop" in prod

if SUBPATH:
    FORCE_SCRIPT_NAME = SUBPATH           # makes reverse()/resolve_url add the prefix
    STATIC_URL = f"{SUBPATH}/static/"
    MEDIA_URL  = f"{SUBPATH}/media/"
else:
    STATIC_URL = "/static/"
    MEDIA_URL  = "/media/"

# Use route NAMES so Django will reverse them (and pick up FORCE_SCRIPT_NAME)
LOGIN_URL = "login"              # not a path; this is the auth view name
LOGIN_REDIRECT_URL = "index"     # your catalog index route name
LOGOUT_REDIRECT_URL = "index"

# The absolute path to the directory where collectstatic will collect static files for deployment.
STATIC_ROOT = Path(os.environ.get("STATIC_ROOT", str(BASE_DIR / "staticfiles")))

# For hard disk file storage
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", str(BASE_DIR / "media")))

# Timestamped upload archive — one folder per successful upload.
# Set RAW_UPLOADS_ROOT= (empty) to disable archiving.
RAW_UPLOADS_ROOT = os.environ.get("RAW_UPLOADS_ROOT", str(BASE_DIR / "raw-uploads"))



ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
# Django's test Client and some tooling use this host.
if DEBUG and "testserver" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = [*ALLOWED_HOSTS, "testserver"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Add our new application
    # This object was created for us in in /catalog/apps.py
    'catalog.apps.CatalogConfig',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "loop.middleware.ApprovedGateMiddleware",

]

APPROVED_GROUP_NAME = "Approved"
APPROVED_BYPASS_SUPERUSERS = True
AWAITING_APPROVAL_URL_NAME = "awaiting_approval"

ROOT_URLCONF = 'loop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loop.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.environ.get("SQLITE_PATH", str(BASE_DIR / "db.sqlite3"))),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Renamed message tag correspondences to play nice with Bootstrap
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Static file serving.
# https://whitenoise.readthedocs.io/en/stable/django.html#add-compression-and-caching-support
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

FILE_UPLOAD_PERMISSIONS = 0o644  # rw-r--r-- (no execute permissions)
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755  # rwxr-xr-x (directories need execute for traversal)

# trust your real host & HTTPS when behind a proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# good to have when serving forms from your domain
CSRF_TRUSTED_ORIGINS = (
    [f"http://{h}" for h in ALLOWED_HOSTS if "." in h or "localhost" in h] +
    [f"https://{h}" for h in ALLOWED_HOSTS if "." in h]
)

if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://127.0.0.1:8000",
        "http://localhost:8000",
    ]

#-- Email Settings --

# Default: print emails to console in dev
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"  # default in dev
)
DEFAULT_FROM_EMAIL   = os.environ.get("DEFAULT_FROM_EMAIL", "Loop <noreply@loop.mintaka.arch.jhu.edu>")
EMAIL_HOST           = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT           = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER      = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD  = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS        = os.environ.get("EMAIL_USE_TLS", "1") == "1"
EMAIL_USE_SSL        = os.environ.get("EMAIL_USE_SSL", "0") == "1"
EMAIL_TIMEOUT        = 10

# Optional niceties
EMAIL_SUBJECT_PREFIX = "[Loop]"

# avoid infinite redirect in dev / localhost
if os.environ.get("DJANGO_DEBUG") == "True":
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_DOMAIN = None

# Toggle for the on-write embedding refresh hooks in catalog/signals.py.
# Set EMBEDDINGS_ON_WRITE=0 in the environment to bypass the sentence-
# transformers load on uploads (useful for tests, low-RAM dev containers,
# or any environment where the backfill command is the only thing expected
# to populate ml_embeddings).
EMBEDDINGS_ON_WRITE = os.environ.get("EMBEDDINGS_ON_WRITE", "1") != "0"

# Preload the sentence-transformers model in a background thread during app
# startup so the first semantic-search request doesn't pay the ~5s
# model-load tax. Disabled automatically for management commands that don't
# serve HTTP traffic. Set EMBEDDINGS_PRELOAD=0 to opt out entirely.
EMBEDDINGS_PRELOAD = os.environ.get("EMBEDDINGS_PRELOAD", "1") != "0"

# Minimum cosine score required for a semantic-search hit to surface on the
# browse page. For sentence-transformers/all-MiniLM-L6-v2 on short structured
# material/recipe text, observed scores cluster as:
#   >= 0.70   strong match (synonym / direct term overlap)
#   0.60-0.70 related (same domain, partial overlap)
#   0.50-0.60 weak / thematic noise
#   <  0.50   unrelated
# The default 0.55 trims the worst noise while leaving borderline-related
# hits visible. Lower it if the catalog is small enough that every hit
# matters; raise it as the dataset grows and noise piles up.
SEMANTIC_SCORE_THRESHOLD = float(os.environ.get("SEMANTIC_SCORE_THRESHOLD", "0.55"))

# MongoDB Configuration
import mongoengine
from urllib.parse import urlparse, urlunparse

MONGODB_URI = os.environ.get("MONGODB_URI", "mongodb://localhost:27017/loop")
mongoengine.connect(host=MONGODB_URI, tz_aware=True)


def _default_raw_uri(primary_uri: str) -> str:
    """Derive a sensible ``loop_raw`` URI from the primary Mongo URI.

    Keeps host/port/auth identical to the main DB and just swaps the path to
    ``/loop_raw``. This means Docker users only need to set ``MONGODB_URI``
    and the raw connection Just Works against the same Mongo instance.
    """
    parsed = urlparse(primary_uri)
    return urlunparse(parsed._replace(path="/loop_raw"))


# Flat "Raw" database used as a portable file-level backup. Lives under the
# ``raw`` MongoEngine alias; see catalog/raw_db.py. Defaults to the same host
# as ``MONGODB_URI`` so Docker and local dev share a single config knob.
MONGODB_RAW_URI = os.environ.get("MONGODB_RAW_URI", _default_raw_uri(MONGODB_URI))
mongoengine.connect(alias="raw", host=MONGODB_RAW_URI, tz_aware=True)
