# Generated by Django 5.2.4 on 2026-07-16 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['expires_at'], name='catalog_api_expires_52d56e_idx'),
        ),
    ]
